language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm


script:
    - ./vendor/bin/phpunit -c ./tests/travis/phpunit.travis.xml -v

after_script:
    - php vendor/bin/coveralls -v

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 7.0
