
language: node_js
node_js:
  - node

  script:
  -npm run build

  deploy:
    skip_cleanup: true
    provider: script
    script: node deploy.js
    on:
      branch: master

env:
global:
    - FTP_USER=David
    - FTP_PASSWORD=3666
after_success:
    curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://81.221.244.152/USB-FlashDisk-01/

