language: php
dist: trusty
sudo: required

php:
  - '7.0'
 
services:
  - mysql
 
env:
  - CI_ENV=testing
 
before_install:
  - sudo apt-get install lftp
  
before_script:
  - composer update
  - chmod 0777 ./vendor/bin/deploy.sh
 
script: ./vendor/bin/test.sh
 
after_success:
  - ./bin/deploy.sh