language: php

# list any PHP version you want to test against
php:

  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

# change into our php directory
  before_install:
    - cd php

# If there is no script entry then Travis CI will execute
script:
  - phpunit --vendor bin/phpunit.bat --debug --coverage-text test





