language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script: phpenv config-add myconfig.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install

script:
  - phpunit -c app/

