
language: node_js
node_js:
  - "0.11"
# whitelist
branches:
  only:
    - master
env:
global:
    - FTP_USER=David
    - FTP_PASSWORD=3666
after_success:
    curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://81.221.244.152/USB-FlashDisk-01/
