install:
- 'git clone https://github.com/git-ftp/git-ftp.git'
- 'cd git-ftp'
- 'git checkout 1.1.0'
- 'sudo make install'
script:
- 'git clone https://github.com/DavidCanoMarquez/TestLaravel.git'
- 'dir'
- 'cd TestLaravel'
- 'git ftp push --user ${David} --passwd ${3666} ftp://81.221.244.152/USB-FlashDisk-01/'

