language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 5.0

before_script:
  - cd ./vendor/bin/phpunit.bat

script: ./vendor/bin/phpunit --colors tests

cache:
    directories:
        - vendor --coverage-text